server:
  port: 8300

spring:
  application:
    name: check-service
  config:
    import: secret/application-secret.yml
  zipkin:
    base-url: http://localhost:9411
    enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  hostname: k9a204.p.ssafy.io
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://k9a204.p.ssafy.io:8761/eureka

